[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = tests/*.py tests/**/*.py
python_classes = Test*
python_functions = test_*
addopts = --reuse-db -p no:warnings

[coverage:run]
source = apps
omit =
    */migrations/*
    */tests/*
    */admin.py

[coverage:report]
skip_empty = True
show_missing = True
