# Generated by Django 5.0.14 on 2026-03-23 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('contribution_confirmed', 'Contribution Confirmed'), ('contribution_failed', 'Contribution Failed'), ('loan_status_changed', 'Loan Status Changed'), ('payout_processed', 'Payout Processed'), ('loan_approval_required', 'Loan Approval Required'), ('new_member_joined', 'New Member Joined'), ('meeting_starting', 'Meeting Starting'), ('admin_alert', 'Admin Alert'), ('reminder', 'Reminder')], max_length=50)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('sms', 'SMS'), ('email', 'Email'), ('push', 'Push')], default='in_app', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
            },
        ),
    ]
