# Generated by Django 5.0.14 on 2026-08-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('contribution_confirmed', 'Contribution Confirmed'), ('contribution_failed', 'Contribution Failed'), ('loan_status_changed', 'Loan Status Changed'), ('payout_processed', 'Payout Processed'), ('loan_approval_required', 'Loan Approval Required'), ('new_member_joined', 'New Member Joined'), ('meeting_starting', 'Meeting Starting'), ('group_status', 'Group Status'), ('group_invite', 'Group Invite'), ('admin_alert', 'Admin Alert'), ('reminder', 'Reminder')], max_length=50),
        ),
    ]
