# Generated by Django 5.0.14 on 2026-05-16 10:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text="Config key, e.g. 'google_translate_api_key'", max_length=100, unique=True)),
                ('value', models.TextField(blank=True, help_text='Config value (encrypted if sensitive)')),
                ('category', models.CharField(choices=[('platform', 'Platform Core'), ('api_data', 'Data & Translation APIs'), ('api_billing', 'Billing & Payment APIs'), ('regional', 'Regional Defaults')], default='platform', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_encrypted', models.BooleanField(default=False, help_text='Whether this value is encrypted at rest')),
                ('is_public', models.BooleanField(default=False, help_text='If true, exposed to lower-level dashboards (manager/user)')),
            ],
            options={
                'db_table': 'system_configuration',
                'ordering': ['category', 'key'],
            },
        ),
    ]
