# Generated by Django 5.0.14 on 2026-06-20 05:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0004_meetingproviderconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(choices=[('kenya', 'Kenya'), ('rwanda', 'Rwanda'), ('ghana', 'Ghana')], max_length=10, unique=True)),
                ('currency', models.CharField(max_length=5)),
                ('central_bank_name', models.CharField(max_length=150)),
                ('max_loan_interest_rate_monthly', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recommended_loan_interest_rate_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('source_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_country_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'country_policy',
                'ordering': ['country'],
            },
        ),
    ]
