# Generated by Django 5.0.14 on 2026-06-20 08:52

from django.db import migrations, models


def remove_unsupported_meeting_providers(apps, schema_editor):
    MeetingProviderConfiguration = apps.get_model('admin_portal', 'MeetingProviderConfiguration')
    MeetingProviderConfiguration.objects.exclude(provider_code='daily').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0005_countrypolicy'),
    ]

    operations = [
        migrations.RunPython(remove_unsupported_meeting_providers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='meetingproviderconfiguration',
            name='provider_code',
            field=models.CharField(choices=[('daily', 'Daily.co')], default='daily', max_length=30),
        ),
    ]
