# Generated by Django 5.0.14 on 2026-07-03 21:14

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0006_alter_meetingproviderconfiguration_provider_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycproviderconfiguration',
            name='client_secret',
            field=common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kycproviderconfiguration',
            name='webhook_secret',
            field=common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meetingproviderconfiguration',
            name='api_key',
            field=common.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meetingproviderconfiguration',
            name='webhook_secret',
            field=common.fields.EncryptedTextField(blank=True),
        ),
    ]
