# Generated by Django 5.0.14 on 2026-07-04 02:11

import common.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0007_alter_kycproviderconfiguration_client_secret_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationProviderConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('provider_code', models.CharField(choices=[('africastalking', "Africa's Talking"), ('custom', 'Custom / Other')], default='africastalking', max_length=30)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('testing', 'Testing'), ('error', 'Error')], default='inactive', max_length=20)),
                ('username', models.CharField(blank=True, help_text="Provider account username (AT: 'sandbox' for sandbox)", max_length=150)),
                ('api_key', common.fields.EncryptedTextField(blank=True)),
                ('sender_id', models.CharField(blank=True, help_text='Registered SMS sender ID / shortcode', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, max_length=20)),
                ('last_test_message', models.TextField(blank=True)),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configured_notification_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_provider_configuration',
                'ordering': ['provider_code', 'environment', 'name'],
                'unique_together': {('provider_code', 'environment')},
            },
        ),
    ]
