# Generated by Django 5.0.14 on 2026-07-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0009_platformbranding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminemailverification',
            name='purpose',
            field=models.CharField(choices=[('admin_registration', 'Admin Registration'), ('admin_password_reset', 'Admin Password Reset')], default='admin_registration', max_length=40),
        ),
    ]
