# Generated by Django 5.0.14 on 2026-08-01 14:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0012_platformbranding_footer_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('kind', models.CharField(choices=[('error', 'Error'), ('slow', 'Slow')], max_length=10)),
                ('actor_email', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='api_event_created_a7e37f_idx'), models.Index(fields=['kind', '-created_at'], name='api_event_kind_fd64be_idx')],
            },
        ),
    ]
