# Generated by Django 5.0.14 on 2026-08-02 14:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0013_apievent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerEnquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('partner_type', models.CharField(choices=[('bank', 'Bank or financial institution'), ('distributor', 'Distributor or agent network'), ('investor', 'Investor'), ('other', 'Other')], default='other', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('source', models.CharField(default='landing', max_length=40)),
            ],
            options={
                'db_table': 'partner_enquiry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='partner_enq_status_3e5f44_idx')],
            },
        ),
    ]
