# Generated by Django 5.0.14 on 2026-08-09 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0011_group_loan_pool_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal_type', models.CharField(choices=[('activate_loan_pool', 'Activate the loan pool'), ('deactivate_loan_pool', 'Deactivate the loan pool'), ('change_loan_terms', 'Change loan terms'), ('change_contribution', 'Change contribution amount'), ('change_savings', 'Change mandatory savings'), ('remove_member', 'Remove a member'), ('dissolve_group', 'Dissolve the group'), ('custom', 'Custom decision')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('quorum_pct', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('pass_pct', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('status', models.CharField(choices=[('open', 'Open'), ('passed', 'Passed'), ('rejected', 'Rejected'), ('expired', 'Expired (no quorum)'), ('cancelled', 'Cancelled')], default='open', max_length=15)),
                ('closes_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('outcome_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='groups.group')),
            ],
            options={
                'db_table': 'governance_proposal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('abstain', 'Abstain')], max_length=10)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='governance.groupproposal')),
                ('voter', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='group_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'governance_vote',
            },
        ),
        migrations.AddIndex(
            model_name='groupproposal',
            index=models.Index(fields=['group', 'status'], name='governance__group_i_8d6daf_idx'),
        ),
        migrations.AddIndex(
            model_name='groupvote',
            index=models.Index(fields=['proposal', 'choice'], name='governance__proposa_0748ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupvote',
            unique_together={('proposal', 'voter')},
        ),
    ]
