# Generated by Django 5.0.14 on 2026-03-23 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('user_login', 'User Login'), ('user_logout', 'User Logout'), ('kyc_submitted', 'KYC Submitted'), ('kyc_verified', 'KYC Verified'), ('kyc_rejected', 'KYC Rejected'), ('group_created', 'Group Created'), ('group_paused', 'Group Paused'), ('group_closed', 'Group Closed'), ('member_joined', 'Member Joined'), ('member_suspended', 'Member Suspended'), ('member_reinstated', 'Member Reinstated'), ('contribution_scheduled', 'Contribution Scheduled'), ('contribution_initiated', 'Contribution Initiated'), ('contribution_confirmed', 'Contribution Confirmed'), ('contribution_failed', 'Contribution Failed'), ('loan_requested', 'Loan Requested'), ('loan_chair_approved', 'Loan Chair Approved'), ('loan_chair_rejected', 'Loan Chair Rejected'), ('loan_treasurer_approved', 'Loan Treasurer Approved'), ('loan_treasurer_rejected', 'Loan Treasurer Rejected'), ('loan_admin_approved', 'Loan Admin Approved'), ('loan_admin_rejected', 'Loan Admin Rejected'), ('loan_disbursed', 'Loan Disbursed'), ('loan_repayment_received', 'Loan Repayment Received'), ('payout_processed', 'Payout Processed'), ('invite_sent', 'Invite Sent'), ('invite_accepted', 'Invite Accepted'), ('admin_action', 'Admin Action'), ('transaction_pin_changed', 'Transaction PIN Changed'), ('password_changed', 'Password Changed'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled')], max_length=50)),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('previous_state', models.JSONField(blank=True, help_text='State of the object before mutation', null=True)),
                ('new_state', models.JSONField(blank=True, help_text='State of the object after mutation', null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='groups.group')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
    ]
