# Generated by Django 5.0.14 on 2026-05-02 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('groups', '0006_alter_group_chairperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='target_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='groups.group'),
        ),
    ]
