# Generated by Django 5.0.14 on 2026-07-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_target_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_login', 'User Login'), ('user_logout', 'User Logout'), ('kyc_submitted', 'KYC Submitted'), ('kyc_verified', 'KYC Verified'), ('kyc_rejected', 'KYC Rejected'), ('group_created', 'Group Created'), ('group_paused', 'Group Paused'), ('group_closed', 'Group Closed'), ('group_activated', 'Group Activated'), ('group_verified', 'Group Verified'), ('group_rejected', 'Group Rejected'), ('member_joined', 'Member Joined'), ('member_suspended', 'Member Suspended'), ('member_reinstated', 'Member Reinstated'), ('member_exited', 'Member Exited'), ('contribution_scheduled', 'Contribution Scheduled'), ('contribution_initiated', 'Contribution Initiated'), ('contribution_confirmed', 'Contribution Confirmed'), ('contribution_failed', 'Contribution Failed'), ('loan_requested', 'Loan Requested'), ('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('loan_chair_approved', 'Loan Chair Approved'), ('loan_chair_rejected', 'Loan Chair Rejected'), ('loan_treasurer_approved', 'Loan Treasurer Approved'), ('loan_treasurer_rejected', 'Loan Treasurer Rejected'), ('loan_admin_approved', 'Loan Admin Approved'), ('loan_admin_rejected', 'Loan Admin Rejected'), ('loan_disbursed', 'Loan Disbursed'), ('loan_repayment_received', 'Loan Repayment Received'), ('payout_processed', 'Payout Processed'), ('payout_triggered', 'Payout Triggered (legacy)'), ('invite_sent', 'Invite Sent'), ('invite_accepted', 'Invite Accepted'), ('reconciliation_item_action', 'Reconciliation Item Action'), ('admin_action', 'Admin Action'), ('transaction_pin_changed', 'Transaction PIN Changed'), ('transaction_pin_instantiated', 'Transaction PIN Instantiated'), ('phone_verified', 'Phone Verified'), ('password_reset', 'Password Reset'), ('password_changed', 'Password Changed'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled')], max_length=50),
        ),
    ]
