# Generated by Django 5.0.14 on 2026-08-09 05:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('bug', 'Something is broken'), ('payment', 'Payment or money issue'), ('account', 'Account or login'), ('question', 'General question'), ('suggestion', 'Suggestion'), ('other', 'Other')], default='other', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='feedback/')),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('severity', models.CharField(choices=[('normal', 'Normal'), ('serious', 'Serious')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('escalated', 'Escalated to super admin')], default='open', max_length=15)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['country', 'status'], name='feedback_fe_country_42c219_idx'), models.Index(fields=['status', 'severity'], name='feedback_fe_status_f30933_idx')],
            },
        ),
    ]
