# Generated by Django 5.0.14 on 2026-03-23 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=5)),
                ('interest_rate_monthly', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_weeks', models.PositiveIntegerField()),
                ('purpose', models.CharField(max_length=255)),
                ('purpose_detail', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_chair', 'Pending Chairperson'), ('pending_treasurer', 'Pending Treasurer'), ('pending_admin', 'Pending Platform Admin'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('active', 'Active'), ('repaid', 'Repaid'), ('defaulted', 'Defaulted'), ('rejected', 'Rejected')], default='pending_chair', max_length=25)),
                ('chair_approved_at', models.DateTimeField(blank=True, null=True)),
                ('chair_rejection_reason', models.TextField(blank=True, null=True)),
                ('treasurer_approved_at', models.DateTimeField(blank=True, null=True)),
                ('treasurer_rejection_reason', models.TextField(blank=True, null=True)),
                ('admin_approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_rejection_reason', models.TextField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('disbursement_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('fully_repaid_at', models.DateTimeField(blank=True, null=True)),
                ('admin_approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_approved_loans', to=settings.AUTH_USER_MODEL)),
                ('borrower', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('chair_approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chair_approved_loans', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='groups.group')),
                ('treasurer_approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasurer_approved_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loans_loan',
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='upcoming', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='loans.loan')),
            ],
            options={
                'db_table': 'loans_loan_repayment',
            },
        ),
    ]
