# Generated by Django 5.0.14 on 2026-03-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_admin_approved_by_alter_loan_borrower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='defaulted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
