# Generated by Django 5.0.14 on 2026-07-04 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_groupmember_one_active_group_per_member'),
        ('loans', '0003_loan_defaulted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRepaymentPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(max_length=5)),
                ('method', models.CharField(default='mpesa', max_length=30)),
                ('mobile_number', models.CharField(max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('platform_reference', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('disputed', 'Disputed')], default='initiated', max_length=20)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayment_payments', to='groups.group')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_payments', to='loans.loan')),
                ('member', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayment_payments', to=settings.AUTH_USER_MODEL)),
                ('repayment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='loans.loanrepayment')),
            ],
            options={
                'db_table': 'loans_repayment_payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider_reference'], name='loans_repay_provide_010fb1_idx'), models.Index(fields=['repayment', 'status'], name='loans_repay_repayme_3cd6d9_idx')],
            },
        ),
    ]
