# Generated by Django 5.0.14 on 2026-03-23 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributions', '0001_initial'),
        ('groups', '0001_initial'),
        ('loans', '0001_initial'),
        ('payouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('contribution', 'Contribution'), ('payout', 'Payout'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('service_fee', 'Service Fee'), ('interest', 'Interest'), ('refund', 'Refund'), ('reconciliation_adjustment', 'Reconciliation Adjustment')], max_length=40)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=5)),
                ('running_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField()),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('hash', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='groups.group')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries_recorded', to=settings.AUTH_USER_MODEL)),
                ('related_contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contributions.contribution')),
                ('related_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='loans.loan')),
                ('related_payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payouts.payout')),
            ],
            options={
                'db_table': 'ledger_entry',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyLedgerCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('merkle_root_hash', models.CharField(help_text='SHA-256 Merkle root of all transactions for this day', max_length=64)),
                ('transaction_count', models.PositiveIntegerField()),
                ('total_volume', models.DecimalField(decimal_places=2, max_digits=14)),
                ('exported_to_s3', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ledger_checkpoints', to='groups.group')),
            ],
            options={
                'db_table': 'ledger_daily_checkpoint',
                'unique_together': {('group', 'date')},
            },
        ),
    ]
