# Generated by Django 5.0.14 on 2026-03-23 17:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.JSONField(help_text='Flexible mapping matching key necessities')),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ledger_system_configuration',
            },
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='running_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
