# Generated by Django 5.0.14 on 2026-07-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_banking_standard_ledger_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='running_balance',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=14),
        ),
    ]
