# Generated by Django 5.0.14 on 2026-03-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='transaction_pin',
            field=models.CharField(blank=True, help_text='Argon2id universally hashed 4-digit verification code', max_length=255),
        ),
    ]
