# Generated by Django 5.0.14 on 2026-03-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_next_of_kin_phone_user_transaction_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='transaction_pin',
            field=models.CharField(blank=True, help_text='Argon2id hashed 4-digit transaction verification code', max_length=255),
        ),
    ]
