# Generated by Django 5.0.14 on 2026-03-24 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phoneotp_attempt_count_phoneotp_max_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='transaction_pin_hash',
        ),
    ]
