# Generated by Django 5.0.14 on 2026-05-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_transaction_pin_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('chairperson', 'Chairperson'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary'), ('platform_admin', 'Platform Admin'), ('super_admin', 'Super Admin')], default='member', max_length=20),
        ),
    ]
