# Generated by Django 5.0.14 on 2026-05-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_bank_account_number_user_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred languages (max 2)'),
        ),
    ]
