# Generated by Django 5.0.14 on 2026-07-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_transaction_pin_lockout'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('phone_verify', 'Phone Verification'), ('password_reset', 'Password Reset')], default='phone_verify', max_length=20),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='code',
            field=models.CharField(help_text='Hashed OTP — never stored in plaintext', max_length=128),
        ),
    ]
