# Generated by Django 5.0.14 on 2026-03-23 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=5)),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('mtn_momo', 'MTN MoMo'), ('bank', 'Bank Transfer')], max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('platform_reference', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('initiated', 'Initiated'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='groups.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contributions_contribution',
            },
        ),
    ]
