# Generated by Django 5.0.14 on 2026-05-16 08:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Display name, e.g. 'Equity Bank Kenya'", max_length=150)),
                ('provider_code', models.CharField(choices=[('jenga_ke', 'Jenga (Equity Bank Kenya)'), ('jenga_rw', 'Jenga (Equity Bank Rwanda)'), ('ecobank_gh', 'Ecobank Ghana'), ('mtn_momo', 'MTN MoMo'), ('mpesa', 'M-Pesa (Daraja)'), ('airtel', 'Airtel Money'), ('custom', 'Custom / Other')], default='custom', max_length=30)),
                ('country', models.CharField(choices=[('kenya', 'Kenya'), ('rwanda', 'Rwanda'), ('ghana', 'Ghana')], max_length=10)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('testing', 'Testing'), ('error', 'Error')], default='inactive', max_length=20)),
                ('api_key', models.TextField(blank=True, help_text='API key / Consumer key')),
                ('api_secret', models.TextField(blank=True, help_text='API secret / Consumer secret')),
                ('merchant_code', models.CharField(blank=True, help_text='Merchant / business code', max_length=100)),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Provider-specific extras (e.g. RSA private key path, paybill)')),
                ('base_url', models.URLField(blank=True, help_text='Provider API base URL (sandbox or live)')),
                ('webhook_url', models.URLField(blank=True, help_text='Our webhook URL registered with the provider')),
                ('webhook_secret', models.TextField(blank=True, help_text='Secret used to verify inbound webhook signatures')),
                ('supports_collections', models.BooleanField(default=True)),
                ('supports_disbursements', models.BooleanField(default=True)),
                ('supports_mobile_money', models.BooleanField(default=True, help_text='Provider natively bridges to mobile money (e.g. Jenga → M-Pesa)')),
                ('supported_mobile_methods', models.JSONField(blank=True, default=list, help_text="e.g. ['mpesa', 'airtel'] — methods bridged via this bank")),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, max_length=20)),
                ('last_test_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('configured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configured_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_bank_provider',
                'ordering': ['country', 'name'],
                'unique_together': {('country', 'provider_code', 'environment')},
            },
        ),
        migrations.CreateModel(
            name='ProviderApiLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], max_length=10)),
                ('endpoint', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_logs', to='payments.bankprovider')),
            ],
            options={
                'db_table': 'payment_provider_api_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
