# Generated by Django 5.0.14 on 2026-07-03 21:14

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_jenga_accounts_provider_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankprovider',
            name='api_key',
            field=common.fields.EncryptedTextField(blank=True, help_text='API key / Consumer key'),
        ),
        migrations.AlterField(
            model_name='bankprovider',
            name='api_secret',
            field=common.fields.EncryptedTextField(blank=True, help_text='API secret / Consumer secret'),
        ),
        migrations.AlterField(
            model_name='bankprovider',
            name='extra_config',
            field=common.fields.EncryptedJSONField(blank=True, default=dict, help_text='Provider-specific extras (e.g. RSA private key, paybill)'),
        ),
        migrations.AlterField(
            model_name='bankprovider',
            name='webhook_secret',
            field=common.fields.EncryptedTextField(blank=True, help_text='Secret used to verify inbound webhook signatures'),
        ),
    ]
