# Generated by Django 5.0.14 on 2026-08-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_bankprovider_api_key_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankprovider',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bankprovider',
            name='region',
            field=models.CharField(blank=True, help_text="Area served within the country, e.g. 'Coast' or 'Western'. Blank = country-wide (universal bank for the whole country).", max_length=80),
        ),
        migrations.AlterField(
            model_name='bankprovider',
            name='provider_code',
            field=models.CharField(choices=[('jenga_ke', 'Equity Bank Kenya (Jenga)'), ('jenga_rw', 'Equity Bank Rwanda (Jenga)'), ('absa_ke', 'Absa Bank Kenya'), ('coop_ke', 'Co-operative Bank Kenya'), ('ecobank_gh', 'Ecobank Ghana'), ('mtn_momo', 'MTN MoMo'), ('mpesa', 'M-Pesa (Daraja)'), ('airtel', 'Airtel Money'), ('custom', 'Custom / Other')], default='custom', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentprovideraccount',
            name='account_type',
            field=models.CharField(choices=[('trust', 'Main Trust / Custody'), ('savings', 'Group Savings'), ('loan', 'Loan Disbursement'), ('fee', 'Company / Charges Revenue'), ('collection', 'Collection'), ('payout', 'Payout'), ('settlement', 'Settlement / Clearing'), ('wallet', 'Wallet'), ('reconciliation', 'Reconciliation')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='bankprovider',
            unique_together={('country', 'provider_code', 'environment', 'region')},
        ),
    ]
