# Generated by Django 5.0.14 on 2026-08-09 20:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_bankprovider_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueSweep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('source_account_ref', models.CharField(blank=True, max_length=100)),
                ('target_account_ref', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending transfer'), ('completed', 'Completed'), ('blocked', 'Blocked (no company account)'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_revenue_sweep',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['country', 'currency', 'status'], name='payment_rev_country_907de1_idx')],
            },
        ),
    ]
