# Generated by Django 5.0.14 on 2026-03-23 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rotation_position', models.PositiveIntegerField()),
                ('cycle_number', models.PositiveIntegerField()),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=5)),
                ('method', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='upcoming', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='groups.group')),
                ('processed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='payouts_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payouts_payout',
            },
        ),
    ]
