# Generated by Django 5.0.14 on 2026-08-09 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_group_region_group_sub_region'),
        ('payouts', '0003_expand_payout_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['processing', 'provider_processing', 'completed', 'paid'])), fields=('group', 'recipient', 'cycle'), name='uniq_active_payout_per_group_cycle_recipient'),
        ),
    ]
