# Generated by Django 5.0.14 on 2026-03-23 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(choices=[('kenya', 'Kenya'), ('rwanda', 'Rwanda'), ('ghana', 'Ghana')], max_length=10)),
                ('max_members', models.PositiveIntegerField(default=20)),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('contribution_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('harvest', 'Harvest Season')], max_length=20)),
                ('contribution_day', models.PositiveIntegerField()),
                ('harvest_start_month', models.PositiveIntegerField(blank=True, null=True)),
                ('harvest_end_month', models.PositiveIntegerField(blank=True, null=True)),
                ('rotation_savings_pct', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
                ('loan_pool_pct', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('max_loan_multiplier', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('loan_term_weeks', models.PositiveIntegerField(default=12)),
                ('loan_interest_rate_monthly', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('rotation_method', models.CharField(choices=[('sequential', 'Sequential'), ('random', 'Random Draw'), ('manual', 'Manual')], default='sequential', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='active', max_length=20)),
                ('invite_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('invite_expires_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(max_length=5)),
                ('trust_account_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('chairperson', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='chaired_groups', to=settings.AUTH_USER_MODEL)),
                ('treasurer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasured_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_group',
            },
        ),
        migrations.CreateModel(
            name='GroupInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.CharField(max_length=255)),
                ('contact_type', models.CharField(max_length=10)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invites', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='groups.group')),
                ('invited_by', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_invite',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rotation_position', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('left', 'Left')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_member',
                'unique_together': {('group', 'user')},
            },
        ),
    ]
