# Generated by Django 5.0.14 on 2026-03-23 18:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_user_groupmember_member_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('late_contribution', 'Late Contribution'), ('missed_meeting', 'Missed Meeting'), ('loan_default', 'Loan Default')], max_length=30)),
                ('penalty_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('grace_period_days', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_rules', to='groups.group')),
            ],
            options={
                'db_table': 'groups_penalty_rule',
            },
        ),
        migrations.CreateModel(
            name='RotationCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('locked', 'Locked')], default='open', max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='groups.group')),
            ],
            options={
                'db_table': 'groups_rotation_cycle',
                'unique_together': {('group', 'cycle_number')},
            },
        ),
        migrations.CreateModel(
            name='RotationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle_number', models.PositiveIntegerField()),
                ('scheduled_payout_date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_schedules', to='groups.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_rotation_schedule',
                'unique_together': {('group', 'cycle_number'), ('group', 'member')},
            },
        ),
    ]
