# Generated by Django 5.0.14 on 2026-03-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_penaltyrule_rotationcycle_rotationschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotationcycle',
            name='total_contributions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='rotationcycle',
            name='total_payouts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
