# Generated by Django 5.0.14 on 2026-03-24 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_rotationcycle_total_contributions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rotationschedule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='left_at',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='exited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rotationschedule',
            name='is_paid_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='accepted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='invited_by',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='member',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('exited', 'Exited'), ('deceased', 'Deceased')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='rotationschedule',
            name='member',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rotationschedule',
            unique_together={('group', 'cycle_number', 'member')},
        ),
    ]
