# Generated by Django 5.0.14 on 2026-07-03 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_group_mandatory_savings_pending_gate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('active', 'pending_approval', 'pending_session_refresh', 'suspended'))), fields=('member',), name='one_active_group_per_member'),
        ),
    ]
