# Generated by Django 5.0.14 on 2026-07-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_groupmember_one_active_group_per_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='sub_region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
