# Generated by Django 5.0.14 on 2026-08-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_group_region_group_sub_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='loan_pool_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
