# Generated by Django 5.0.14 on 2026-06-20 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_group_mandatory_savings_pending_gate'),
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('as_needed', 'As Needed')], default='monthly', max_length=20)),
                ('notice_days', models.PositiveSmallIntegerField(default=7)),
                ('quorum_percent', models.PositiveSmallIntegerField(default=60)),
                ('majority_percent', models.PositiveSmallIntegerField(default=51)),
                ('provider_mode', models.CharField(choices=[('platform_default', 'Platform Default'), ('google_meet', 'Google Meet When Enabled')], default='platform_default', max_length=30)),
                ('attendance_tracking', models.BooleanField(default=True)),
                ('minutes_required', models.BooleanField(default=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_settings', to='groups.group')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_meeting_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meetings_settings',
            },
        ),
    ]
