# Generated by Django 5.0.14 on 2026-06-20 08:52

from django.db import migrations, models


def normalize_provider_mode(apps, schema_editor):
    MeetingSettings = apps.get_model('meetings', 'MeetingSettings')
    MeetingSettings.objects.exclude(provider_mode='daily').update(provider_mode='daily')


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meetingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='video_provider',
            field=models.CharField(default='daily', max_length=30),
        ),
        migrations.AddField(
            model_name='meeting',
            name='video_room_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='meeting',
            name='video_room_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='meetingsettings',
            name='provider_mode',
            field=models.CharField(choices=[('daily', 'Daily.co')], default='daily', max_length=30),
        ),
        migrations.RunPython(normalize_provider_mode, migrations.RunPython.noop),
    ]
